import React from 'react';
import './LegalPages.css';

function PrivacyPolicy() {
  return (
    <div className="legal-page">
      <section className="legal-hero">
        <div className="container">
          <h1>Privacy Policy</h1>
          <p className="legal-date">Last Updated: June 2, 2026</p>
        </div>
      </section>

      <section className="legal-content">
        <div className="container">
          <div className="legal-section">
            <h2>1. Introduction</h2>
            <p>
              Welcome to Smart Collection Analytics Platform. We respect your privacy and are committed to protecting 
              your personal data. This privacy policy explains how we collect, use, and safeguard your information 
              when you use our platform.
            </p>
          </div>

          <div className="legal-section">
            <h2>2. Information We Collect</h2>
            <h3>2.1 Account Information</h3>
            <p>When you sign up using Google OAuth, we collect:</p>
            <ul>
              <li>Your name and email address from your Google account</li>
              <li>Area selection you choose during registration</li>
              <li>User ID generated by our authentication system</li>
            </ul>

            <h3>2.2 Usage Data</h3>
            <p>We automatically collect information about your use of the platform:</p>
            <ul>
              <li>File upload activity and processing timestamps</li>
              <li>Pages visited and features used</li>
              <li>Browser type and device information</li>
              <li>Session duration and interaction patterns</li>
            </ul>

            <h3>2.3 Collection Data</h3>
            <p>When you upload Excel files:</p>
            <ul>
              <li>We process division, area, and plaza-level collection data</li>
              <li>Data is used to generate summaries and analytics</li>
              <li>Processed data is stored securely in our database</li>
            </ul>
          </div>

          <div className="legal-section">
            <h2>3. How We Use Your Information</h2>
            <p>We use the collected information for the following purposes:</p>
            <ul>
              <li><strong>Service Delivery:</strong> To provide analytics, reports, and dashboard functionality</li>
              <li><strong>Authentication:</strong> To verify your identity and manage your account access</li>
              <li><strong>Personalization:</strong> To show you data relevant to your selected area</li>
              <li><strong>Notifications:</strong> To send automated Telegram reports (if you opt in)</li>
              <li><strong>Improvement:</strong> To analyze usage patterns and enhance platform features</li>
              <li><strong>Security:</strong> To detect and prevent fraud, abuse, or security issues</li>
            </ul>
          </div>

          <div className="legal-section">
            <h2>4. Data Storage and Security</h2>
            <p>We implement industry-standard security measures to protect your data:</p>
            <ul>
              <li>All data is encrypted in transit using HTTPS/TLS protocols</li>
              <li>Authentication handled by Google OAuth 2.0</li>
              <li>Database hosted on secure cloud infrastructure (Supabase)</li>
              <li>Access controls and role-based permissions implemented</li>
              <li>Regular security audits and updates</li>
              <li>Automatic session management with secure token handling</li>
            </ul>
          </div>

          <div className="legal-section">
            <h2>5. Data Sharing and Disclosure</h2>
            <p>We do not sell your personal data. We may share information only in these circumstances:</p>
            <ul>
              <li><strong>With Your Consent:</strong> When you explicitly authorize data sharing</li>
              <li><strong>Service Providers:</strong> Third-party services that help us operate (Google Auth, Supabase, hosting providers)</li>
              <li><strong>Legal Requirements:</strong> When required by law or to protect our rights</li>
              <li><strong>Business Transfers:</strong> In case of merger, acquisition, or sale of assets</li>
            </ul>
            <p>
              Note: Telegram notifications are sent via Telegram Bot API. Only aggregated summary data is included 
              in these notifications, not individual user information.
            </p>
          </div>

          <div className="legal-section">
            <h2>6. Your Rights and Choices</h2>
            <p>You have the following rights regarding your personal data:</p>
            <ul>
              <li><strong>Access:</strong> Request a copy of the personal data we hold about you</li>
              <li><strong>Correction:</strong> Update or correct inaccurate information</li>
              <li><strong>Deletion:</strong> Request deletion of your account and associated data</li>
              <li><strong>Opt-Out:</strong> Disable Telegram notifications or other optional features</li>
              <li><strong>Data Portability:</strong> Export your data in a machine-readable format</li>
              <li><strong>Withdraw Consent:</strong> Revoke consent for data processing where applicable</li>
            </ul>
            <p>To exercise these rights, contact us via the information provided in the Contact section below.</p>
          </div>

          <div className="legal-section">
            <h2>7. Data Retention</h2>
            <p>
              We retain your personal data only as long as necessary to provide our services and comply with legal obligations:
            </p>
            <ul>
              <li>Account information: Retained while your account is active</li>
              <li>Collection data: Stored for analytical and comparison purposes</li>
              <li>Usage logs: Typically retained for 90 days for troubleshooting</li>
              <li>After account deletion: Data is permanently removed within 30 days</li>
            </ul>
          </div>

          <div className="legal-section">
            <h2>8. Cookies and Tracking</h2>
            <p>We use browser local storage for:</p>
            <ul>
              <li>Authentication session management</li>
              <li>Caching user area preferences for faster load times</li>
              <li>Remembering UI preferences and settings</li>
            </ul>
            <p>
              We do not use third-party advertising cookies or tracking pixels. You can clear local storage 
              through your browser settings at any time.
            </p>
          </div>

          <div className="legal-section">
            <h2>9. Third-Party Services</h2>
            <p>Our platform integrates with the following third-party services:</p>
            <ul>
              <li><strong>Google OAuth:</strong> For authentication (governed by Google's Privacy Policy)</li>
              <li><strong>Supabase:</strong> For database and authentication backend</li>
              <li><strong>Telegram Bot API:</strong> For optional notification delivery</li>
              <li><strong>Web Hosting:</strong> For platform deployment and delivery</li>
            </ul>
            <p>These services have their own privacy policies which govern their use of your information.</p>
          </div>

          <div className="legal-section">
            <h2>10. Children's Privacy</h2>
            <p>
              Our platform is not intended for users under the age of 18. We do not knowingly collect personal 
              information from children. If you believe we have inadvertently collected data from a child, 
              please contact us immediately.
            </p>
          </div>

          <div className="legal-section">
            <h2>11. Changes to This Policy</h2>
            <p>
              We may update this privacy policy from time to time to reflect changes in our practices or legal 
              requirements. We will notify users of significant changes by posting a notice on our platform or 
              sending an email. Your continued use of the platform after changes constitutes acceptance of the 
              updated policy.
            </p>
          </div>

          <div className="legal-section">
            <h2>12. Contact Us</h2>
            <p>If you have questions, concerns, or requests regarding this privacy policy or your personal data:</p>
            <div className="contact-info">
              <p><strong>Developer:</strong> Md. Rezaul Karim RCM</p>
              <p><strong>WhatsApp:</strong> <a href="https://wa.me/8801712394851">+880 1712-394851</a></p>
              <p><strong>Facebook:</strong> <a href="https://www.facebook.com/rezaul2000">facebook.com/rezaul2000</a></p>
              <p><strong>Website:</strong> <a href="https://rezaulkarim.shop">rezaulkarim.shop</a></p>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}

export default PrivacyPolicy;
